# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

i = 1
j = 2
s = 0

while i+j < 4000000:
    if i%2 == 0:
        s = s+i
    if j%2 == 0:
        s = s+j
    i = i + j
    j = i + j

# The above while loop doesn't add the last even Fibonacci numbers to the sum
if i%2 == 0:
    s = s+i
if j%2 == 0:
    s = s+j

print(s)

